name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        uses: php-actions/composer@v5
      - name: PHPUnit Tests
        run: composer run test
      - name: PHPUnit Tests Coverage
        run: composer run test:coverage
      - name: Generate Test Coverage Badge
        uses: timkrase/phpunit-coverage-badge@v1.2.0
        with:
          coverage_badge_path: coverage-badge.svg
          push_badge: true
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
